# Define la imagen base
FROM python:3.11.2-alpine3.17

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY gestor_usuarios/ .
EXPOSE 5000

CMD ["python", "server_usr.py"]
